default_language_version:
    python: python3
default_stages: [commit, push]
fail_fast: false
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: fix-byte-order-marker
            name: fix-byte-order-marker
            description: removes UTF-8 byte order marker
          - id: trailing-whitespace
            name: trailing-whitespace
            description: Trims trailing whitespace
            args: [--markdown-linebreak-ext=md]
          - id: end-of-file-fixer
            name: end-of-file-fixer
            description: Makes sure files end in a newline and only a newline
          - id: check-json
            name: check-json
            description: Attempts to load all json files to verify syntax
          - id: check-toml
            name: check-toml
            description: Attempts to load all TOML files to verify syntax
          - id: check-symlinks
            name: check-symlinks
            description: Checks for symlinks which do not point to anything
          - id: check-added-large-files
            name: check-added-large-files
            description: Prevent files larger than 1 MB from being committed
            args: [ "--maxkb=1024", '--enforce-all' ]
          - id: check-case-conflict
            name: check-case-conflict
            description: Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
          - id: end-of-file-fixer
            name: end-of-file-fixer
            description: Makes sure files end in a newline and only a newline
          - id: mixed-line-ending
            name: mixed-line-ending
            description: Replaces or checks mixed line ending
          - id: check-ast
            name: check-ast
            description: Simply check whether files parse as valid python
          - id: debug-statements
            name: debug-statements
            description: Check for debugger imports and py37+ breakpoint() calls in python source
          - id: detect-aws-credentials
            name: detect-aws-credentials
            description: Checks for the existence of AWS/Minio secrets that you have set up
            args: [--allow-missing-credentials]
          - id: detect-private-key
            name: detect-private-key
            description: Checks for the existence of private keys.
          - id: requirements-txt-fixer
            name: requirements-txt-fixer
            description: Sorts entries in requirements.txt and removes incorrect entries
          - id: check-merge-conflict
            name: check-merge-conflict
            description: Check for files that contain merge conflict strings
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
          - id: python-check-mock-methods
            name: check-mock-methods
            description: Prevent common mistakes of assert mck.not_called(), assert mck.called_once_with(...) and mck.assert_called.
          - id: python-use-type-annotations
            name: python-use-type-annotations
            description: Enforce that python3.6+ type annotations are used instead of type comments
          - id: python-check-blanket-noqa
            name: python-check-blanket-noqa
            description: Enforce that noqa annotations always occur with specific codes.
    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: v0.991
    #   hooks:
    #       - id: mypy
    #         name: mypy - static type checker for Python
    #         description: Static type checker for Python
    #         files: ^src/
    #         exclude: ^tests/
    #         args: [--ignore-missing-imports]
    #         # additional_dependencies: [types-all]
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.3.0
      hooks:
          - id: add-trailing-comma
            name: add-trailing-comma
            description: Automatically add trailing commas to calls and literals.
    - repo: https://github.com/PyCQA/flake8
      rev: 5.0.4
      hooks:
          - id: flake8
            name: flake8 - check the style and quality of some python code
            description: Python tool that glues together pycodestyle, pyflakes, mccabe, and third-party plugins to check the style and quality of some python code
            additional_dependencies:
                - flake8-bugbear
                - flake8-variables-names
                - pep8-naming
                - flake8-print
                - flake8-quotes
                - flake8-broken-line
                - flake8-comprehensions
                - flake8-eradicate
                - flake8-typing-imports==1.12.0
    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
          - id: black
            name: black - consistent Python code formatting
            description: The uncompromising Python code formatter
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
            name: isort - sort Python imports
            description: Library to sort imports
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
            name: pyupgrade - upgrade syntax for newer versions of the language
            description: Automatically upgrade syntax for newer versions of the language
            args: [--py36-plus]
    - repo: https://github.com/jendrikseipp/vulture
      rev: v2.6
      hooks:
          - id: vulture
            name: vulture - finds unused code in Python programs
            description: Finds unused code in Python programs
##########################################################################################
# Git
##########################################################################################
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.37.1
      hooks:
          - id: commitizen
            stages: [commit-msg]
##########################################################################################
# Documentation
##########################################################################################
    - repo: https://github.com/executablebooks/mdformat
      rev: 0.7.16
      hooks:
          - id: mdformat
            name: mdformat - Markdown formatter that can be used to enforce a consistent style in Markdown files
            description: Markdown formatter that can be used to enforce a consistent style in Markdown files
            additional_dependencies:
              - mdformat-black
              - mdformat-beautysh
            exclude: CHANGELOG.md
    - repo: https://github.com/myint/docformatter
      rev: v1.5.0
      hooks:
          - id: docformatter
            name: docformatter - formats docstrings to follow PEP 257
            description: Formats docstrings to follow PEP 257
            args: [--in-place]
    - repo: https://github.com/terrencepreilly/darglint
      rev: v1.8.1
      hooks:
          - id: darglint
            name: darglint - Python documentation linter
            description: A python documentation linter which checks that the docstring description matches the definition.
            args: ["-z", long]
