[tool.black]
line-length = 88
color = true
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
      \.egg
    | \.eggs
    | \.git
    | \.hg
    | \.dvc
    | \.mypy_cache
    | \.pytest_cache
    | \.nox
    | \.tox
    | \.venv_prod
    | \.venv_dev
    | _build
    | build
    | dist
    | setup.py
)
'''

# `isort` configurations
[tool.isort]
# https://github.com/timothycrosley/isort
py_version = 38
profile = "black"
force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip_gitignore = true
color_output = true
#known_typing = ["typing", "types", "typing_extensions", "mypy", "mypy_extensions"]

[tool.vulture]
paths = ["src"]
min_confidence = 65
